package:
  name: pyro4
  version: 4.40

source:
  path: ..

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gensim = gensim:main
    #
    # Would create an entry point called gensim that calls gensim.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - serpent >=1.11

  run:
    - python
    - serpent >=1.11

test:
  # Python imports
  imports:
    - Pyro4

about:
  home: http://radimrehurek.com/Pyro4
  license: MIT
